sudo: required
dist: trusty

language: python

python:
  - "3.6.5"

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker-compose up -d neo4j.nqc
  - docker pull agrdocker/agr_neo4j_env:latest
  - docker build -t agrdocker/agr_loader_run:latest .
  
script:
  - docker-compose up agr_loader_test
  - docker-compose run agr_loader_test pytest --verbose
