sudo: required
dist: xenial

language: python

python:
  - "3.6.5"

services:
  - docker

before_install:
  - docker-compose up -d neo4j.nqc
  - docker pull agrdocker/agr_neo4j_env:latest
  - docker build -t agrdocker/agr_loader_run:latest .
  
script:
  - docker-compose up agr_loader_test
<<<<<<< HEAD
  - docker-compose run agr_loader_test_unit_tests
=======
  - docker-compose run agr_loader_test pytest --verbose
>>>>>>> develop
