sudo: required
dist: trusty

language: python

services:
  - docker

before_install:
  - docker-compose up -d neo4j.nqc
  - docker pull agrdocker/agr_neo4j_env:develop
  - docker build -f Dockerfile_env -t agrdocker/agr_loader_env:develop .
  - docker build -t agrdocker/agr_loader_run:develop .
  
script:
  - docker-compose up agr_loader_test
