version: "3.2"

services:
  neo4j.nqc:
    container_name: neo4j.nqc
    image: agrdocker/agr_neo4j_env:latest
    volumes:
      - type: volume
        source: agr_data_share
        target: /var/lib/neo4j/import
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    networks:
      - esnet
    environment:
      - NEO4J_dbms_memory_heap_maxSize=24576m
      - NEO4J_dbms_memory_heap_initialSize=4096m

  neo4j.qc:
    container_name: neo4j.qc
    image: agrdocker/agr_neo4j_qc_data_image:build
    volumes:
      - type: volume
        source: agr_data_share
        target: /var/lib/neo4j/import
        volume:
          nocopy: true
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    networks:
      - esnet
    environment:
      - NEO4J_dbms_memory_heap_maxSize=24576m
      - NEO4J_dbms_memory_heap_initialSize=4096m

  agr_loader:
    image: agrdocker/agr_loader_run:latest
    volumes:
      - type: volume
        source: agr_data_share
        target: /usr/src/app/tmp
        volume:
          nocopy: true
    networks:
      - esnet
    environment:
     - PYTHONUNBUFFERED=1
     - TEST_SET=False
     - UNIT_TESTS=False
     - NEO4J_NQC_HOST=neo4j.nqc
     - NEO4J_NQC_PORT=7687

  agr_loader_test:
    image: agrdocker/agr_loader_run:latest
    volumes:
      - type: volume
        source: agr_data_share
        target: /usr/src/app/tmp
        volume:
          nocopy: true
    networks:
      - esnet
    environment:
     - PYTHONUNBUFFERED=1
     - TEST_SET=True
     - UNIT_TESTS=False
     - NEO4J_NQC_HOST=neo4j.nqc
     - NEO4J_NQC_PORT=7687

networks:
  esnet:

volumes:
  agr_data_share:
