schemaVersion: 1.0.1.4
releaseVersion: 4.0.0
SPECIES: [Species]
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, SARS-CoV-2]

ONTOLOGY:
  - MI

INTERACTION-MOL: [COMBINED]


# not really bit want to check construct etl.
CONSTRUCT: [ZFIN, WB, FB]
# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
