schemaVersion: 1.0.1.2
releaseVersion: 3.1.1
SPECIES: [Species]
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, SARS-CoV-2]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
ProteinSequence: [ProteinSequence]
GFF: [FB, WB, ZFIN, MGI, RGD, SGD]
ONTOLOGY:
  - SO

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7

