schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB, SGD, WB, ZFIN, RGD, Human]
Allele: [FB, WB, ZFIN, RGD]
Expression: [FB, SGD, WB, ZFIN, Human]
Phenotype: [FB, SGD, WB, ZFIN, RGD, Human]
Disease: [FB, SGD, WB, ZFIN, RGD, Human]
Ontology: [GO, SO, DO, MI]
Orthology: [FB, SGD, WB, ZFIN, RGD, Human]