schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB]
Allele: [FB]
Expression: [FB]
Phenotype: [FB]
Disease: [FB]
Ontology:
  - ZFA 
  - ZFS 
  - WBBT 
  - CL 
  - FBDV 
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - UBERON
Orthology: [FB]