schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [SGD, ZFIN]
Expression: [SGD, ZFIN]
Disease: [SGD]
Ontology:
  - GO
  - SO
  - MMO
  - ZFA
  - ZFS
  - CL
  - BSPO
  - UBERON
Orthology: [SGD, ZFIN]
ExpressionRibbon: [other]
GeneDiseaseOrtho: [other]
Closure: [other]