schemaVersion: 1.0.0.9
releaseVersion: 2.3.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ALLELE: [FB, WB, ZFIN, RGD, MGI]
PHENOTYPE: [FB, SGD, WB, ZFIN, RGD, MGI]
AGM: [ZFIN, MGI, RGD]
SQTR: [ZFIN]
ONTOLOGY:
  - SO

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 7
Neo4jTransactorThreads: 3



