schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [ZFIN]
Ontology:
  - GO
  - SO
  - DO
  - MI 
  - ZFA 
  - ZFS 
  - WBBT 
  - CL 
  - FBDV 
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - UBERON
Expression: [ZFIN]