schemaVersion: 1.0.0.9
releaseVersion: 2.3.0
BGI: [RGD]
ALLELE: [RGD]
FASTA: [Rnor60]
VARIATION: [RGD]
ONTOLOGY:
  - SO
VEP: [RGD]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7





