schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [SGD, ZFIN, WB]
Allele: [ZFIN, WB]
Disease: [SGD, ZFIN, WB]
Ontology:
  - DO
  - SO
Orthology: [SGD, ZFIN, WB]
GeneDiseaseOrtho: [other]
Closure: [other]