schemaVersion: 1.0.1.0
releaseVersion: 3.0.0
BGI: [FB, MGI, SGD, HUMAN]
CONSTRUCT: [FB]
ALLELE: [FB]
#EXPRESSION: [FB, SGD, WB, ZFIN, RGD, MGI]
#PHENOTYPE: [FB, SGD, WB, ZFIN, RGD, MGI]
DAF: [FB, SGD, HUMAN]
GAF: [FB, SGD, HUMAN]
#GeoXref: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
#GENEEEXPRESSIONATLASSITEMAP: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
VARIATION: [FB]
GFF: [FB]
AGM: [MGI]
#SQTR: [ZFIN]
ONTOLOGY:
  - SO
  - GO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - ECOMAP
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP
#ExpressionAtlas: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ORTHO: [FB, SGD, MGI, HUMAN]
#ExpressionRibbon: [ExpressionRibbon]
#ExpressionRibbonOther: [ExpressionRibbonOther]
GeneDiseaseOrtho: [GeneDiseaseOrtho]
Closure:
  - GO
  - SO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP
#INTERACTION-MOL: [COMBINED]
GeneDescriptions: [FB, SGD, MGI, HUMAN]
VEPTRANSCRIPT: [FB, MGI]
VEP: [FB, MGI]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7




