schemaVersion: 1.0.1.2
releaseVersion: 3.1.1
SPECIES: [Species]
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, SARS-CoV-2]
HTPDATASET: [SGD, FB, WB, ZFIN, RGD, MGI]
HTPDATASAMPLE: [SGD, FB, WB, ZFIN, RGD, MGI]
ONTOLOGY:
  - SO
