schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, Human]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7