schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB, ZFIN, MGI]
EXPRESSION: [FB, ZFIN, MGI]
Ontology:
  - GO
  - SO
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
ExpressionRibbon: [ExpressionRibbon]
ExpressionRibbonOther: [ExpressionRibbonOther]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 7
Neo4jTransactorThreads: 3