schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [SGD, ZFIN]
Expression: [SGD]
Disease: [SGD]
Ontology:
  - GO
  - SO
  - MMO
  - UBERON
Orthology: [SGD]
ExpressionRibbon: [other]
SearchClosure: [other]