schemaVersion: 1.0.1.3
releaseVersion: 3.2.0
SPECIES: [Species]
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, SARS-CoV-2]
PHENOTYPE: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
DAF: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ONTOLOGY:
  - SO
  - DOID
GENEPHENOCROSSREFERENCE: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]


# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7