schemaVersion: 1.0.0.9
releaseVersion: 2.3.0
BGI: [FB]
ONTOLOGY:
  - MI
Interactions: [MolecularInteraction]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
