schemaVersion: 1.0.1.0
releaseVersion: 3.0.0
ALLELE: [ZFIN, FB]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
VARIATION: [ZFIN, FB]
GFF: [FB, ZFIN]
ONTOLOGY:
  - SO
VEPTRANSCRIPT: [ZFIN, FB]
VEP: [ZFIN, FB]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7















