schemaVersion: 1.0.1.4
releaseVersion: 4.0.0
SPECIES: [Species]
BGI: [ZFIN]
ALLELE: [ZFIN]
FASTA: [GRCz11]
VARIATION: [ZFIN]
GFF: [ZFIN]
ONTOLOGY:
  - SO
VEPTRANSCRIPT: [ZFIN]
VEPGENE: [ZFIN]
ProteinSequence: [ProteinSequence]
FileTransactorThreads: 10
Neo4jTransactorThreads: 7
