schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
ALLELE: [FB, WB, ZFIN, RGD, MGI]
DAF: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Ontology:
  - SO
  - DO
  - MI
ORTHO: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
ExpressionRibbon: [ExpressionRibbon]
ExpressionRibbonOther: [ExpressionRibbonOther]
GeneDiseaseOrtho: [GeneDiseaseOrtho]


# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 7
Neo4jTransactorThreads: 3