schemaVersion: 1.0.1.3
releaseVersion: 3.2.0
SPECIES: [Species]
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, SARS-CoV-2]
ALLELE: [FB, WB, ZFIN, RGD, MGI]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
VARIATION: [FB, WB, ZFIN, RGD, MGI]
GFF: [FB, WB, ZFIN, MGI, RGD, SGD]
ONTOLOGY:
  - SO
VEPTRANSCRIPT: [FB, WB, ZFIN, RGD, MGI]
VEPGENE: [FB, WB, ZFIN, RGD, MGI]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
