schemaVersion: 1.0.1.0
releaseVersion: 3.0.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
CONSTRUCT: [ZFIN, WB]
ALLELE: [FB, WB, ZFIN, RGD, MGI]
DAF: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ONTOLOGY:
  - SO
  - DOID

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7





















