schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [ZFIN, MGI, WB, SGD, FB, Human, RGD]
ALLELE: [ZFIN, MGI, WB, FB, RGD]
VARIATION: [ZFIN, MGI, WB, SGD, FB, Human, RGD]
Ontology:
  - SO

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 7
Neo4jTransactorThreads: 3
