schemaVersion: 1.0.0.9
releaseVersion: 2.3.0
BGI: [ZFIN, RGD, MGI, HUMAN]
ALLELE: [ZFIN, RGD, MGI]
DAF: [ZFIN, RGD, MGI, HUMAN]
AGM: [ZFIN, MGI, RGD]
SQTR: [ZFIN]
ONTOLOGY:
  - SO
  - DOID

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
