schemaVersion: 1.0.1.2
releaseVersion: 3.1.1
SPECIES: [Species]
HTPDATASET: [SGD, FB, WB, ZFIN, RGD, MGI]
HTPDATASAMPLE: [SGD, FB, WB, ZFIN, RGD, MGI]
ONTOLOGY:
  - SO
  - GO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - ECOMAP
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP
  - OBI
  - BTO
  - CHEBI

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7


