schemaVersion: 1.0.0.9
releaseVersion: 3.0.0
BGI: [ZFIN, RGD, WB]
CONSTRUCT: [WB, ZFIN, RGD]
ALLELE: [WB, ZFIN, RGD]
ONTOLOGY:
  - SO

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7


