schemaVersion: 1.0.0.9
releaseVersion: 2.3.0
BGI: [ZFIN, RGD, MGI, HUMAN]
ALLELE: [ZFIN, RGD, MGI]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
VARIATION: [ZFIN, RGD, MGI]
ONTOLOGY:
  - SO
  - DOID

VEP: [FB, WB, ZFIN, RGD, MGI]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
