schemaVersion: 1.0.1.0
releaseVersion: 3.1.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
CONSTRUCT: [ZFIN, WB, FB]
ALLELE: [FB, WB, ZFIN, RGD, MGI]
AGM: [ZFIN, MGI, RGD, WB]
SQTR: [ZFIN]
ONTOLOGY:
  - SO
  - GO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - ECOMAP
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7