schemaVersion: 1.0.1.0
releaseVersion: 3.1.0
ONTOLOGY:
  - GO
  - DOID
  - ZFA

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7