schemaVersion: 1.0.1.0
releaseVersion: 3.0.0
BGI: [ZFIN, MGI, WB]
CONSTRUCT: [ZFIN, WB]
ALLELE: [ZFIN, MGI, WB]
PHENOTYPE: [ZFIN, MGI, WB]
AGM: [ZFIN, MGI, WB]
SQTR: [ZFIN]
ONTOLOGY:
  - SO
  - GO

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7












