schemaVersion: 1.0.0.9
releaseVersion: 2.3.0
BGI: [ZFIN, MGI, RGD]
ALLELE: [ZFIN, RGD, MGI]
EXPRESSION: [ZFIN, RGD, MGI]
PHENOTYPE: [ZFIN, RGD, MGI]
DAF: [ZFIN, RGD, MGI]
GAF: [ZFIN, RGD, MGI]
GeoXref: [ZFIN, RGD, MGI]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
GENEEEXPRESSIONATLASSITEMAP: [ZFIN, RGD, MGI]
VARIATION: [ZFIN, RGD, MGI]
AGM: [ZFIN, MGI, RGD]
SQTR: [ZFIN]
ONTOLOGY:
  - GO
  - SO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - ECOMAP
ExpressionAtlas: [ZFIN, RGD, MGI]
ExpressionRibbon: [ExpressionRibbon]
ExpressionRibbonOther: [ExpressionRibbonOther]
ORTHO: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Closure:
  - GO
  - SO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
Interactions: [MolecularInteraction]
GeneDescriptions: [ZFIN, RGD, MGI]
VEP: [ZFIN, RGD, MGI]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
