schemaVersion: 1.0.0.8
releaseVersion: 2.2.0
BGI: [ZFIN]
ALLELE: [ZFIN]
DAF: [ZFIN]
GAF: [ZFIN]
Ontology:
  - GO
  - SO
  - DO
GeneDescriptions: [ZFIN]

FileTransactorThreads: 7
Neo4jTransactorThreads: 3