schemaVersion: 1.0.1.1
releaseVersion: 3.1.0
GFF: [FB, WB, ZFIN, MGI, RGD]


# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7




