schemaVersion: 1.0.1.4
releaseVersion: 4.0.0
SPECIES: [Species]
BGI: [ZFIN]
DAF: [ZFIN]
GAF: [ZFIN]
ONTOLOGY:
  - SO
  - GO
  - DOID
GeneDescriptions: [ZFIN]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
