schemaVersion:
  regex: ^(\d(\.\d){3})$
  required: True
releaseVersion: 
  regex: ^(\d(\.\d){3})$
  required: True
BGI:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Allele: 
  type: list
  allowed: [FB, WB, ZFIN, RGD, MGI]
Disease: 
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Phenotype: 
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Expression: 
  type: list
  allowed: [FB, SGD, WB, ZFIN, MGI, Human]
GOAnnot:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Ontology:
  type: list
  allowed: 
    - GO 
    - SO 
    - DO 
    - MI 
    - ZFA 
    - ZFS 
    - WBBT 
    - CL 
    - FBDV 
    - FBBT
    - FBCV
    - MMUSDV
    - BSPO
    - MMO
    - WBLS
    - EMAPA
    - MA
    - UBERON
Orthology:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]