schemaVersion:
  regex: ^(\d(\.\d){3})$
  required: True
releaseVersion: 
  regex: ^(\d(\.\d){3})$
  required: True
BGI:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Allele: 
  type: list
  allowed: [FB, WB, ZFIN, RGD, MGI]
Disease: 
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Phenotype: 
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Expression: 
  type: list
  allowed: [FB, SGD, WB, ZFIN, MGI, Human]
SO: 
  required: True
  type: boolean
GO:
  required: True
  type: boolean
DO:
  required: True
  type: boolean
MI:
  required: True
  type: boolean