schemaVersion:
  regex: ^(\d(\.\d){3})$
  required: True
releaseVersion: 
  regex: ^(\d(\.\d){3})$
  required: True
BGI:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
ALLELE:
  type: list
  allowed: [FB, WB, ZFIN, RGD, MGI]
DAF:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
PHENOTYPE:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI]
EXPRESSION:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI]
GOAnnot:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
GeoXref:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Ontology:
  type: list
  allowed: 
    - GO 
    - SO 
    - DO 
    - MI 
    - ZFA 
    - ZFS 
    - WBBT 
    - CL
    - FBBT
    - FBCV
    - MMUSDV
    - BSPO
    - MMO
    - WBLS
    - EMAPA
    - MA
    - ECO
    - UBERON
Orthology:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
ExpressionRibbon:
  type: list
  allowed: [ExpressionRibbon]
GeneDiseaseOrtho:
  type: list
  allowed: [GeneDiseaseOrtho]
Closure:
  type: list
  allowed: 
    - GO 
    - SO 
    - DO 
    - MI 
    - ZFA 
    - ZFS 
    - WBBT 
    - CL 
    - FBCV
    - FBBT
    - MMUSDV
    - BSPO
    - MMO
    - WBLS
    - EMAPA
    - MA
    - ECO
    - UBERON
Interactions:
  type: list
  allowed: [MolecularInteraction]
FileTransactorThreads:
  type: integer
  required: True
Neo4jTransactorThreads:
  type: integer
  required: True